export const headingFonts = [
  "Roboto Slab",
  "Merriweather",
  "Playfair Display",
  "Noto Serif Display",
  "Noto Serif",
  "PT Serif",
  "Inria Serif",
  "Instrument Serif",
  "Bitter",
  "Libre Baskerville",
  "Abril Fatface",
  "Lora",
];
export const bodyFonts = [
  "DM Sans",
  "Inter",
  "Mulish",
  "Roboto",
  "Montserrat",
  "Poppins",
  "Source Sans Pro",
  "Fira Sans",
  "Open Sans",
  "Lato",
  "Raleway",
  "Manrope",
  "Bricolage Grotesque",
  "Inria Sans",
  "Public Sans",
  "Space Grotesk",
  "Work Sans",
  "IBM Plex Sans",
  "Nunito Sans",
  "Karla",
  "Rubik",
  "Heebo",
];
